version: "3.7"
services:    
  nodejs:
    build: ./app/
    container_name: nodejs
    restart: on-failure
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - NODE_PORT=80
    networks: 
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./app/:/app
      - /app/node_modules

  mongo:
    image: mongo:4.2-bionic
    restart: on-failure
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - ./data/mongo:/data/db

networks:
  frontend:
  backend:

volumes:
  app:
  data:
